
spring:
  application:
    name: spring-transaction-exam

  threads:
    virtual:
      enabed: true

  # SQL ???? ?? ??
  sql:
    init:
      mode: always  # ?? SQL ???? ??
      schema-locations: classpath:data/schema.sql  # ??? ???? ??
      data-locations: classpath:data/data.sql  # ??? ???? ??
      continue-on-error: false  # ?? ?? ? ?? ??
      separator: ";"  # SQL ?? ???

  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/exam1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: zeeemeee
    password: qwer1234!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 300000  # 5?
      connection-timeout: 20000  # 20?
      max-lifetime: 1200000  # 20?

  jpa:
    defer-datasource-initialization: false # SQL ????? Hibernate ??? ?? ??
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # ?? ?? ??

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
